disqus_awesome: true
disqus_devel: true
google_analytics_code: UA-12495571-3
permalink: /:year/:month/:day/:title.html
#permalink: /posts/:title.html
pygments: true
pet:
url:
exclude: 
- readme.md
- Rakefile
#- archives
- highlight.css
